---
- name: Installer et configurer un serveur web Apache
  hosts: webservers
  become: true
  vars:
    http_port: 80
    max_clients: 200

  tasks:
    - name: Installation packets
      apt:
        name: { item }
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      loop:
        - tcpdump
        - htop 
        - tshark

    - name: Installer le paquet Apache (pour RedHat)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Démarrer le service Apache (pour RedHat)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Déployer un fichier HTML de test
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Bienvenue</title>
          </head>
          <body>
            <h1>Bienvenue sur votre serveur web!</h1>
            <p>Ce serveur est géré par Ansible.</p>
          </body>
          </html>

    - name: Assurer que le service Apache écoute sur le port {{ http_port }}
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen {{ http_port }}'
        state: present
      notify: Redémarrer Apache
      when: ansible_os_family == "Debian"

    - name: Assurer que le service Apache écoute sur le port {{ http_port }} (pour RedHat)
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen {{ http_port }}'
        state: present
      notify: Redémarrer Apache (pour RedHat)
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"

    - name: Redémarrer Apache (pour RedHat)
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"
