---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install python3
  ansible.builtin.apt:
    name: "python3"
    state: present

- name: Install python packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ broadcast_scan_python_packages }}"
